export const appPath = {
  home: "/home",
  student: "/student",
  login: "/login",
  documentOne: "/generalrequest",
  documentTwo: "/returntostudy",
  documentThree: "/pleasestatus",
  documentFour: "/enrollmentlow",
  documentFive: "/maintainstatus",
  documentSix: "/adddelay",
  documentSeven: "/withdrawdelay",
  documentEight: "/grouptransfer",
  documentNine: "/latepayment",
  documentTen: "/coursecomparison",
  documentEleven: "/changedata",
  documentTwelve: "/resignstudent",
  documentThirteen: "/studydocument",
  documentFourteen: "/behaviorcertify",
  documentFifteen: "/graduation",
  documentSixteen: "/soccessdelay",
  documentSeventeen: "/requestmoreseats",
  documentEighteen: "/document-eighteen",

  authority: {
    root: "/authority",
  },
};
