export const ADMIN_LOGIN_LOADING = "ADMIN_LOGIN_LOADING";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED";
export const ADMIN_INITIAL = "ADMIN_INITIAL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
