export const AUTHORITY_LOGIN_LOADING = "AUTHORITY_LOGIN_LOADING";
export const AUTHORITY_LOGIN_SUCCESS = "AUTHORITY_LOGIN_SUCCESS";
export const AUTHORITY_LOGIN_FAILED = "AUTHORITY_LOGIN_FAILED";
export const AUTHORITY_INITIAL = "AUTHORITY_INITIAL";
export const AUTHORITY_LOGOUT = "AUTHORITY_LOGOUT";
